### ISSUE TITLE
Improve documentation for the replace is a function use case

### ISSUE THREAD

**Issue by dlmiles** [bomsy/grunt-regex-replace#10]
The argument to the replace function use case are:

argument[0] is the full string matched
argument[1] is the first parenthesized substring match
argument[2] is the second parenthesized substring match
argument[3] is the Nth parenthesized substring match ...

see https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions and the section "Using parenthesized substring matches"

**Comment by bomsy** [comment]
Nice one! will update.

**Comment by bomsy** [comment]
Published new version 0.2.7 with fix.
