### ISSUE TITLE
Add an option to suppress logging

### ISSUE THREAD

**Issue by Jessevanbekkum** [bomsy/grunt-regex-replace#12]
At the moment this plugin generates a lot of logging, two lines for each file. This generates many pages of logging which obscures our more important stuff. Is it possible to suppress this?

If not, is this an interesting feature to add?

**Comment by bomsy** [comment]
This might be good to add, i'm not sure sure of what would be the best way to do this. One option would be
- Setting environment variables, which would be used to determine logging.
- Adding a property to specify logging

**Comment by Jessevanbekkum** [comment]
I have not a lot of experience with grunt, so I do not know what the common practices are, but if I look at other systems the ideal case would be both. A property to set a default value in your build configuration that is shared between developers, and an environment variable that overrides the property for occasional debugging.

**Comment by Jessevanbekkum** [comment]
If I look at http://gruntjs.com/api/grunt.log, there is also the --debug flag. That is probably the best solution.

Log any errors, such as invalid regexes, on the error level, log the normal stuff, such as the

```
File '...' replace complete.
replace ... action completed.
```
on debug level.
