### ISSUE TITLE
Grunt 1.0.x support

### ISSUE THREAD

**Issue by evilaliv3** [bomsy/grunt-regex-replace#17]
Right know if one install grunt-regex-replace with grunt 1.0.1 get an error:
```The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!```

This is caused by the strict requirement for grunt 0.4.0 specified in https://github.com/bomsy/grunt-regex-replace/blob/master/package.json

**Comment by bomsy** [comment]
Hey thanks! Will test with grunt 1.x and get out a new release. Will probably be a major release.

**Comment by bomsy** [comment]
Just released 0.3.0. Please try that. thanks
