### ISSUE TITLE
Provide a destination instead of overwriting original?

### ISSUE THREAD

**Issue by spAnser** [bomsy/grunt-regex-replace#19]
Any chance a destination can be added so it doesn't overwrite the original file it is modifying?

**Comment by bomsy** [comment]
Yeah. i can do this.

**Comment by bomsy** [comment]
`
    src: ['bar/bla.js', 'bar/foo.js'],
    dest: ['/bar/bla.js', 'foo/foo.js']
    actions: [{ 
       search: 'foo',
       replace: 'bar'
    }]
 }`

**Comment by spAnser** [comment]
Yeah that looks good.

**Comment by bomsy** [comment]
0.4.0 released! check it out.
